### ISSUE TITLE
Chromecast icon not visible

### ISSUE THREAD

**Issue by Micoder-dev** [THEOplayer/android-ui#17]

**Comment by MattiasBuelens** [comment]
THEOplayer Android UI supports casting to Chromecast. If you're using [the DefaultUI component](https://theoplayer.github.io/android-ui/api/ui/com.theoplayer.android.ui/-default-u-i.html), you'll find the Chromecast button in the top right corner. Alternatively, you can place a [ChromecastButton](https://theoplayer.github.io/android-ui/api/ui/com.theoplayer.android.ui/-chromecast-button.html) in your custom UI.

Note that the Chromecast button is only shown when Android detects an available Chromecast receiver in the local network (when [Player.castState](https://theoplayer.github.io/android-ui/api/ui/com.theoplayer.android.ui/-player/cast-state.html) is [AVAILABLE](https://docs.theoplayer.com/api-reference/android/com/theoplayer/android/api/cast/chromecast/PlayerCastState.html#AVAILABLE)). Is this perhaps what you're seeing? If not, could you describe your issue in more detail?

**Comment by ceyhun-o** [comment]
Hi @Micoder-dev,

Do you have any updates to share here? Could you resolve the issue?

**Comment by Micoder-dev** [comment]
> Hi @Micoder-dev,
> 
> Do you have any updates to share here? Could you resolve the issue?

@ceyhun-o Yes, for Chromecast I have created my own lib

**Comment by ceyhun-o** [comment]
Hi @Micoder-dev,

[As my colleague explained](https://github.com/THEOplayer/android-ui/issues/17#issuecomment-1719030414), that should not be necessary.

In any case, if you need any assistance on this (or anything else), please reach out to us on our [Service Desk](https://opentelly.atlassian.net/servicedesk/customer/portal/1) with the details and we will gladly help.

I will be closing this one for the moment.

Kind regards,
Ceyhun
