### ISSUE TITLE
compose-bom 2024.02.00 breaks hold and drag functionality of the slider

### ISSUE THREAD

**Issue by ceyhun-o** [THEOplayer/android-ui#24]
**Summary:**
Upgrading to latest `compose-bom` (2024.02.00) seem to partly break the slider and no longer allows holding and dragging the progress bar.

**Steps to Reproduce:**
1. Swap the `compose-bom` version [here](https://github.com/THEOplayer/android-ui/blob/main/gradle/libs.versions.toml#L8) with latest.
2. Build and run the project.
3. Try to hold and drag the progress bar to seek.

**Expected:**
Seek bar should function as expected when holding and dragging.

**Actual:**
Holding and dragging the seek bar doesn't work on the latest `compose-bom`. Short touching a certain position on the slider to seek still functions as expected though.

**Reproduction Rate:**
10/10.

**Device:**
Tested on Pixel 5 (Android 14)

https://github.com/THEOplayer/android-ui/assets/74964451/2fa8dee5-47a2-4aaa-86a6-8d1d50880e32

https://github.com/THEOplayer/android-ui/assets/74964451/2e8b47e7-1b7f-4096-b92a-e203042630b8

**Comment by MattiasBuelens** [comment]
Landed in [1.5.0](https://github.com/THEOplayer/android-ui/releases/tag/v1.5.0).
