### ISSUE TITLE
chrome cast compatibility with core sdk

### ISSUE THREAD

**Issue by mammad-derakhshan** [THEOplayer/android-ui#47]
good morning.
after upgrading the core sdk to 8.1.2, the chrome cast button doesn't work.
not working means, clicking on the cast btn, will not launch the device dialog.
the latest functioning version is 8.0.1
@MattiasBuelens 
thank you

**Comment by MattiasBuelens** [comment]
Thanks for reporting!

From your discussions with @ceyhun-o, we figured out that you're trying to use the `ChromecastButton` *before* setting a source on the player. We hadn't tested this use case, and we can confirm your findings that Open Video UI for Android doesn't handle this correctly.

We're working on a fix in #49. We'll keep you posted with further updates.

**Comment by m-derakhshan** [comment]
thank you.

**Comment by MattiasBuelens** [comment]
The fix has landed in [version 1.9.2](https://github.com/THEOplayer/android-ui/releases/tag/v1.9.2). 🚀

**Comment by m-derakhshan** [comment]
thank you.
